"""Initial migration for Account table

Revision ID: 76e539d83a84
Revises:
Create Date: 2022-12-07 20:56:26.279536

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76e539d83a84"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
